import { IUser } from '@blockspaces/shared/models/users';
import { Injectable, CanActivate, ExecutionContext } from '@nestjs/common';
import { Request } from 'express';


/** Ensures that the endpoint is only accessable by E2E users.
 *  e2e users are auto generated by Cypress testing.
 *  If the user is not an e2e users then no access is allowed.
 */
@Injectable()
export class E2eAuthGuard implements CanActivate {
  canActivate(
    context: ExecutionContext,
  ): boolean | Promise<boolean> {
    const request = context.switchToHttp().getRequest<any>();
    if (request.user.email.includes(`e2e+`) && request.user.email.endsWith('blockspaces.com')) {
      return true;
    } else {
      return false;
    }
  }
}
