export type TermsHtmlProps = {
  /** if true, the title will be show */
  showTitle?: boolean
}

export default function TermsHtml({
  showTitle = false,
}: TermsHtmlProps) {
  return (
    <>
      {showTitle && <h1>Terms of Service</h1>}
      <style>
        {
          `
          body {
            text-align: justify;
          }
          `
        }
      </style>
      <p>Welcome to BlockSpaces! Please read on to learn the rules and restrictions that govern your use of our website(s), products, services, and applications (the “Services,” as further described herein). If you have any questions, comments, or concerns regarding these terms or the Services, please contact us at:</p>
      <center>
        Email: <a href="mailto:legal@blockspaces.com">legal@blockspaces.com</a><br/>
        Phone: 1-813-500-8585<br/>
        Address: 802 E Whiting St., Tampa, FL 33602
      </center>
      <p>PLEASE NOTE THAT YOUR USE OF AND ACCESS TO OUR SERVICES ARE SUBJECT TO THE FOLLOWING TERMS; IF YOU DO NOT AGREE TO ALL OF THE FOLLOWING, DO NOT USE OR ACCESS OUR SERVICES IN ANY MANNER.</p>
      <center><i>Last updated: March 14, 2023</i></center>
      <p>These Terms of Use (these "Terms") are a binding contract between you and BlockSpaces Inc. ("BlockSpaces," "we" and "us"). You must agree to and accept all of the Terms (together with any specific terms and conditions set forth during the onboarding of your account (the "Account Onboarding Terms") and the BlockSpaces <a href="https://www.blockspaces.com/legal/privacy-policy" target="_blank">Privacy Policy</a>, the "Agreement"), or you don't have the right to use the Services in any manner. Your use of the Services in any way means that you agree to all of the terms and conditions of the Agreement, and such terms will remain in effect while you use the Services.</p>
      <p>Please read these Terms carefully. They cover important information about Services provided to you and any charges and fees we bill you. These Terms include information about future changes to these Terms, automatic renewals, limitations of liability, class action waiver, and resolution of disputes by arbitration instead of in court.</p>
      <p>ARBITRATION NOTICE AND CLASS ACTION WAIVER: EXCEPT FOR CERTAIN TYPES OF DISPUTES DESCRIBED IN THE ARBITRATION SECTION DETAILED BELOW, YOU AGREE THAT DISPUTES BETWEEN YOU AND BLOCKSPACES WILL BE RESOLVED BY BINDING, INDIVIDUAL ARBITRATION, AND YOU WAIVE YOUR RIGHT TO PARTICIPATE IN A CLASS ACTION LAWSUIT OR CLASS-WIDE ARBITRATION.</p>
      <h5><strong><em>Children’s Online Privacy Protection Act.</em></strong></h5>
      <p>The Children’s Online Privacy Protection Act (“COPPA”) requires that online service providers obtain parental consent before they knowingly collect personally identifiable information online from children who are under thirteen (13). We do not knowingly collect or solicit personally identifiable information from children under thirteen (13); if you are a child under thirteen (13), please do not attempt to register for or otherwise use the Services or send us any personal information. If we learn we have collected personal information from a child under thirteen (13), we will delete that information as quickly as possible. If you believe that a child under thirteen (13) may have provided us personal information, please contact us at <a href="mailto:contact@blockspaces.com">contact@blockspaces.com</a>.</p>
      <h5><em>Our Services</em></h5>
      <p>BlockSpaces offers managed blockchain infrastructure and prebuilt connectors between various blockchain networks and business applications, which includes the ability to connect to our blockchain cloud minfrastructure, access blockchain nodes, create blockchain endpoints, API integrations, and access other developer tools (the "Services"). If you use this feature of the BlockSpaces service, BlockSpaces will never take custody of or control over the digital assets you earn from using our Services. BlockSpaces acts only as a software and infrastructure provider and not as a counterparty to any transaction with any third party. When using our services, you also are subjecting yourself to the rules and technical default of the specific blockchain protocol that you choose, over which BlockSpaces has no control. BlockSpaces will not be held liable for any decisions you make in connection with your digital assets.</p>
      <p>BlockSpaces offers non-custodial, client-side encrypted Lightning Network infrastructure Services. As part of the services, BlockSpaces may provide liquidity for its customer's nodes with enough Bitcoin to make the lightning channel operational, that liquidity is provided by and remains the property of BlockSpaces at all times. BlockSpaces reserves the right not to provide the initial liquidity and also to close channels to redeem the liquidity at any time without notice. BlockSpaces is a provider of non-custodial software tools &amp; infrastructure services and does not retain, control, own, have access to or otherwise have the ability to revoke, recall, or reset cryptographic keys tied to your digital asset wallet(s). <strong>BlockSpaces is not able to reset passwords for its customer's Lightning wallets. If you lose your password, you will permanently lose access to your Lightning wallet funds.</strong></p>
      <p>BlockSpaces offers non-custodial staking infrastructure services. All customers using our service are also bound by the protocol rules, such as the bonding/unbonding periods, minimum staking requirements, and/or validator fees. BlockSpaces does not pool its customers' funds to achieve higher validator success nor have the ability to do so. BlockSpaces has no discretion over the reward payout periods or the returns, these are all determined by the protocol and other factors unrelated to our services.</p>
      <p>The Content (as defined below) provided by BlockSpaces is for informational purposes only. The Services are not intended to provide financial, investment, tax, or legal advice, and nothing in the Services should be construed as a solicitation or counsel for investment or recommendation for any security by BlockSpaces or any third party.</p>
      <p>You will be required to sign up for an account with an email and password (“BlockSpaces User Account”), and provide us with certain information or data, such as your contact information. You promise to provide us with accurate, complete, and updated registration information about yourself. You may not select as your BlockSpaces User Account a name that you do not have the right to use or another person’s name with the intent to impersonate that person. You may not transfer your account to anyone else or permit a third party to access your account without our prior written permission. You are responsible for the safe keeping of your password.</p> 
      <p>If you lose access to your password to your BlockSpaces account, BlockSpaces provides a password reset option from our website. This is unrelated to any encrypted wallet password(s) and should be kept distinctly separate.</p>
      <h5><em>Representations and Warranties</em></h5>
      <p>You represent and warrant that:</p>
      <ul>
        <li>
          <p>If you are an individual, you are of legal age to form a binding contract and use the Services for a lawful purpose;</p>
        </li>
        <li>
          <p>If you agree to the Agreement on behalf of an organization or entity, you represent and warrant that you are authorized to agree to these Terms on that organization’s or entity’s behalf and bind them to the Agreement (in which case, the references to “you” and “your” in these Terms, except for in this sentence, refer to that organization or entity); You will only use the Services for your own internal, personal use, and not on behalf of or for the benefit of any third party. You will comply with all laws that apply to you, your use of the Services, and your actions and omissions that relate to the Services. If your use of the Services is prohibited by applicable laws, then you aren’t authorized to use the Services. We can’t and won’t be responsible for using the Services in a way that breaks the law; You will not share your account or password with anyone, and you must protect the security of your account and your password and any other access tools or credentials. You’re responsible for any activity associated with your account;</p>
        </li>
        <li>
          <p>You agree that, in connection with the Services, you will not contract with or otherwise do business with any individual, company, organization or other entity, or with, in or involving any country or territory (including North Korea, Cuba, Iran, Sudan, Syria, and Crimea), that is the subject or target of any U.S. or other national government financial and economic sanctions or trade embargoes or otherwise identified on a list of prohibited, sanctioned, debarred, or denied parties, including those imposed, administered or enforced from time to time by the U.S. government through the Office of Foreign Assets Control ("OFAC") of the U.S. Department of Treasury, the Bureau of Industry and Security (“Department of Treasury, the Bureau of Industry and Security (“BIS”) of the U.S. Department of Commerce, or the U.S. Department of State, the United Nationals Security Council, the European Union, or Her Majesty’s Treasury of the United Kingdom (collectively, “Sanctions”), without having first obtained any required license or other government authorization or in any manner which would result in a violation of Sanctions by you or BlockSpaces.</p>
        </li>
        <li>
          <p>Neither you nor nor any of your subsidiaries nor any of your or your subsidiaries' directors, administrators, officers, board of directors (supervisory and management), members or employees is the subject or target of any Sanctions;</p>
        </li>
        <li>
          <p>You have adequate controls and systems in place to screen and are fully responsible for screening, transactions of customers, sub-contractors, suppliers, vendors, and all other third parties who may assist, benefit from, or provide goods or services to, or receive goods or services from, you and to ensure compliance with applicable laws pertaining to Sanctions;</p>
        </li>
        <li>
          <p>You have appropriate procedures in place to comply with (and to ensure timely reporting under) the requirements of the anti-boycott laws and regulations of the United States and other jurisdictions in which BlockSpaces does business;</p>
        </li>
        <li>
          <p>You have adequate policies and procedures in place to ensure that, and will ensure that, the Services provided in connection with the Agreement will not be exported, re-exported, sold, leased or otherwise transferred to, or utilized by, an end-user engaged in any of the following activities: (i) activities related to weapons of mass destruction, including any activities related to the design, development, production or use of: (A) nuclear weapons, materials or facilities; (B) missiles or the support of missile projects; or (C) chemical or biological weapons; (ii) terrorist activities (iii) military end uses in or connected with certain government owned or controlled corporations of such countries as identified by U.S. and other applicable government licensing authorities; (iv) exploration or production of oil and gas in Arctic, deepwater (greater than 500 feet), or shale formations in Russia or in, by, or with Russian companies, territories, or any other entities as identified by BIS and/or OFAC; or (v) for any other purpose not expressly authorized by BlockSpaces.</p>
        </li>
        <li>
          <p>Nothing in this clause is to be construed as authorization by BlockSpaces for you to export, sell, lease, transfer, market, or resell the Services in violation of this Agreement.</p>
        </li>
        <li>
          <p>You will only use the Services for your own internal, personal use and not on behalf of or for the benefit of any third party.</p>
        </li>
        <li>
          <p>You will comply with all laws that apply to you, your use of the Services, and your actions and omissions that relate to the Services. If your use of the Services is prohibited by applicable laws, then you aren’t authorized to use the Services. We can’t and won’t be responsible for your using the Services in a way that breaks the law.</p>
        </li>
        <li>
          <p>You will not share your account or password with anyone, and you must protect the security of your account and your password and any other access tools or credentials. You are responsible for any activity associated with your account.</p>
        </li>
        <li>
          <p>To the extent that software and/or documentation is embedded in or delivered with the Goods and/or Services, the sale of such Goods and/or Services shall not constitute the transfer of ownership rights or title in such software and/or documentation to you, but, subject to the provisions set forth herein, shall only imply a non-exclusive and non-transferable license to Purchaser to use such software and/or documentation in conjunction with and as embedded in or delivered with the Goods and/or Services. To the extent the Parties have agreed that third-party software and/or documentation shall be embedded in or delivered with the Goods and/or Services, You acknowledge and accept that license terms of third parties may apply.</p>
        </li>
      </ul>
      <p>Your use of the Services is subject to the following additional restrictions:</p>
      <p>You represent, warrant, and agree that you will not contribute any Content or User Submission (as each of those terms is defined below) or otherwise use the Services or interact with the Services in a manner that:</p>
      <ul>
        <li>infringes or violates the intellectual property rights or any other rights of anyone else (including BlockSpaces);</li>
        <li>violates, or assists in violation of any law, statute, ordinance, or regulation, including, without limitation, any applicable export control laws, privacy laws, or sanctions programs administered in the countries where BlockSpaces conducts business, including but not limited to the U.S. Department of Treasury’s Office of Foreign Assets Control (“OFAC”), or which involves proceeds of any unlawful activity; or that results in the publication, distribution or dissemination any unlawful material or information; or for any other purpose not reasonably intended by BlockSpaces;</li>
        <li>is dangerous, harmful, fraudulent, deceptive, threatening, harassing, defamatory, obscene, or otherwise objectionable;</li>
        <li>jeopardizes the security of your BlockSpaces account or anyone else’s (such as allowing someone else to log in to the Services as you);</li>
        <li>attempts, in any manner, to obtain the password, account, or other security information from any other user;</li>
        <li>violates the security of any computer network, or cracks any passwords or security encryption codes;</li>
        <li>runs Maillist, Listserv, any form of auto-responder or “spam” on the Services, or any processes that run or are activated while you are not logged into the Services, or that otherwise interferes with the proper working of the Services (including by placing an unreasonable load on the Services’ infrastructure);</li>
        <li>“crawls,” “scrapes,” or “spiders” any page, data, or portion of or relating to the Services or Content (through use of manual or automated means);</li>
        <li>copies or stores any significant portion of the Content; or</li>
        <li>decompiles, reverse engineers, or otherwise attempts to obtain the source code or underlying ideas or information of or relating to the Services.</li>
      </ul>
      <p>A violation of any of the foregoing is grounds for termination of your right to use or access the Services.</p>
      <h5><em>User rights in our Services</em></h5>
      <p>The materials displayed or performed or available on or through the Services, including, but not limited to, text, graphics, data, articles, photos, images, illustrations, information, User Submissions (as defined below), and so forth (all of the foregoing, the “Content”) are protected by copyright and/or other intellectual property laws. You promise to abide by all copyright notices, trademark rules, information, and restrictions contained in any Content you access through the Services, and you won’t use, copy, reproduce, modify, translate, publish, broadcast, transmit, distribute, perform, upload, display, license, sell, commercialize or otherwise exploit for any purpose any Content not owned by you, (i) without the prior consent of the owner of that Content or (ii) in a way that violates someone else’s (including BlockSpaces') rights.</p>
      <p>Subject to these Terms, we grant each user of the Services a worldwide, non-exclusive, non-sublicensable, revocable and non-transferable license to use (i.e., to download and display locally) Content solely for purposes of using the Services. Use, reproduction, modification, distribution, or storage of any Content for other than purposes of using the Services is expressly prohibited without prior written permission from us. You shall not sell, license, rent, or otherwise use or exploit any Content for commercial use or in any way that violates any third-party right. You understand that BlockSpaces owns the Services. You won’t modify, publish, transmit, participate in the transfer or sale of, reproduce (except as expressly provided in this Section), create derivative works based on, or otherwise exploit any of the Services.</p>
      <p>The Services may allow you to copy or download certain Content, but please remember that even where these functionalities exist, all the restrictions in this section still apply.</p>
      <h5><em>User Responsibilities in our Services</em></h5>
      <p>Any Content publicly posted or privately transmitted through the Services is the sole responsibility of the person from whom such Content originated, and you access all such information and Content at your own risk, and we aren’t liable for any errors or omissions in that information or Content or for any damages or loss you might suffer in connection with it. We cannot control and have no duty to take any action regarding how you may interpret and use the Content or what actions you may take as a result of having been exposed to the Content, and you hereby release us from all liability for your having acquired or not acquired Content through the Services.</p>
      <p>You are responsible for all Content you contribute, in any manner, to the Services, and you represent and warrant you have all rights necessary to do so in the manner in which you contribute it. You will keep all your registration information accurate and current. You are responsible for all your activity in connection with the Services.</p>
      <p>If there is a dispute between participants on this site or Services, or between users and any third party, you agree that BlockSpaces is under no obligation to become involved. In the event that you have a dispute with one or more other users, you release BlockSpaces, its directors, officers, employees, agents, and successors from claims, demands, and damages of every kind or nature, known or unknown, suspected or unsuspected, disclosed or undisclosed, arising out of or in any way related to such disputes and/or our Services. You shall and hereby do waive California Civil Code Section 1542 or any similar law of any jurisdiction, which says in substance: “A general release does not extend to claims which the creditor does not know or suspect to exist in his or her favor at the time of executing the release, which, if known by him or her must have materially affected his or her settlement with the debtor.”</p>
      <h5><em>License to BlockSpaces or to Other Users</em></h5>
      <p>Anything you post, upload, share, store, or otherwise provide through the Services is your “User Submission.” Some User Submissions may be viewable by other users. In order to display your User Submissions on the Services (for example, on your account dashboard), and to allow other users to enjoy them (where applicable), you hereby grant BlockSpaces a license to translate, modify (for technical purposes, for example, making sure your content is viewable on a mobile device as well as a computer) and reproduce and otherwise act with respect to such User Submissions, in each case to enable us to operate the Services. This is a license only – your ownership in User Submissions is not affected. Please note that this license is subject to our <a href="https://www.blockspaces.com/legal/privacy-policy" target="_blank">Privacy Policy</a> to the extent it relates to User Submissions that are also your personally-identifiable information.</p>
      <p>If you share a User Submission publicly on the Services and/or in a manner that more than just you or certain specified users can view, or if you provide us (in a direct email or otherwise) with any feedback, suggestions, improvements, enhancements, and/or feature requests relating to the Services (each of the foregoing, a “Public User Submission/Feedback”), then you grant BlockSpaces the license above, as well as a license to display, perform, and distribute your Public User Submission/Feedback for the purpose of making that Public User Submission/Feedback accessible to all BlockSpaces users and providing the Services necessary to do so, as well as all other rights necessary to use and exercise all rights in that Public User Submission/Feedback in connection with the Services and/or otherwise in connection with BlockSpaces' business. Also, you grant all other users of the Services a license to access that Public User Submission, and to use and exercise all rights in it, as permitted by the functionality of the Services.</p>
      <p>You agree that the licenses you grant are royalty-free, perpetual, sublicensable, irrevocable, and worldwide, provided that when you delete your BlockSpaces account, we will stop displaying your User Submissions (other than Public User Submissions, which may remain fully available) to other users (if applicable), but you understand and agree that it may not be possible to completely delete that content from BlockSpaces' records.</p>
      <p>Finally, you understand and agree that BlockSpaces, in performing the required technical steps to provide the Services to our users (including you), may need to make changes to your User Submissions to conform and adapt those User Submissions to the technical requirements of connection networks, devices, services, or media, and the foregoing licenses include the rights to do so.</p>
      <h5><em>Confidentiality</em></h5>
      <p>During the course of performance of the Agreement, each party may be exposed to the other party’s Confidential Information. Each party, on behalf of itself and its employees, contractors and agents (collectively, “Representatives”), agrees not to, except as set forth below or as required by applicable law or regulation, use or disclose the Confidential Information of the disclosing party during or after the term without the prior written consent of the disclosing party.  Each party, on behalf of itself and its Representatives, further agrees to use the same degree of care to protect the disclosing party’s Confidential Information from misuse or disclosure that the receiving party uses with respect to its own Confidential Information, but in no event with less than reasonable care. For the purposes of the Agreement, “Confidential Information” means all non-public information disclosed by one party to the other in connection with the Agreement, whether or not marked as confidential, or which the receiving party should reasonably know to be the confidential information of the disclosing party.</p>
      <h5><em>Modifications to Services and Prices</em></h5>
      <p>In a constant effort to ensure stable performance and provide best in class value in our Services, BlockSpaces reserves the right to modify, suspend or discontinue, temporarily or permanently, any part or all of the Services with or without notice. Prices for all Services are subject to change upon thirty (30) day notice via email, or on the official website. BlockSpaces shall not be liable to you or to any third party for any modification, price change, suspension, or discontinuance of the Service.</p>
      <h5><em>Payment &amp; Billing Terms</em></h5>
      <p>We charge for use of the Services as follows:</p>
      <p>
        <span style={{ textDecoration: 'underline' }}>Paid Services</span>
        . Please see our Payments page  for a description of the fees required for use of the Services. Please note that any payment terms presented to you in the process of using or signing up for the Services are deemed part of the Agreement.
      </p>
      <p>
        <span style={{ textDecoration: 'underline' }}>Billing</span>
        . We may use a third-party payment processor (the “Payment Processor”) to bill you through a payment account linked to your account on the Services (your “Billing Account”) for use of the Services, or we may accept payment in cryptocurrency by payment to our cryptocurrency wallet (or a combination of both). The processing of payments through a Payment Processor will be subject to the terms, conditions and privacy policies of the Payment Processor in addition to this Agreement. Currently, we use Stripe, Inc. as our Payment Processor. You can access Stripe’s Terms of Service at <a href="https://stripe.com/us/checkout/legal" target={"_blank"}>https://stripe.com/us/checkout/legal</a> and their Privacy Policy at <a href="https://stripe.com/us/privacy" target={"_blank"}>https://stripe.com/us/privacy</a>. We are not responsible for error by the Payment Processor. By choosing to use the Services, you agree to pay us, through the Payment Processor or automatically into our cryptocurrency wallet, all charges at the prices then in effect for any use of the Services in accordance with the applicable payment terms, and you authorize us, through the Payment Processor, to charge your chosen payment provider or to automatically receive payment through our cryptocurrency wallet from your account (your “Payment Method”). You agree to make payment using that selected Payment Method. We reserve the right to correct any errors or mistakes that the Payment Processor makes, even if it has already requested or received payment.
      </p>
      <p>
        <span style={{ textDecoration: 'underline' }}>Payment Method</span>
        . The terms of your payment will be based on your Payment Method and may be determined by agreements between you and the financial institution, credit card issuer, or other provider of your chosen Payment Method. If we, through the Payment Processor, do not receive payment from you, you agree to pay all amounts due on your Billing Account upon demand.
      </p>
      <p>
        <span style={{ textDecoration: 'underline' }}>Recurring Billing</span>
        . Some of the Services may consist of an initial period, for which there is a one-time charge, followed by recurring period charges as agreed to by you. By choosing a recurring payment plan, you acknowledge that such Services have an initial and recurring payment feature, and you accept responsibility for all recurring charges before cancellation. WE MAY SUBMIT PERIODIC CHARGES (E.G., MONTHLY) WITHOUT FURTHER AUTHORIZATION FROM YOU UNTIL YOU PROVIDE PRIOR NOTICE (RECEIPT OF WHICH IS CONFIRMED BY US) THAT YOU HAVE TERMINATED THIS AUTHORIZATION OR WISH TO CHANGE YOUR PAYMENT METHOD. SUCH NOTICE WILL NOT AFFECT CHARGES SUBMITTED BEFORE WE REASONABLY COULD ACT. TO TERMINATE YOUR AUTHORIZATION OR CHANGE YOUR PAYMENT METHOD, GO TO ACCOUNT SETTINGS.
      </p>
      <p>
        <span style={{ textDecoration: 'underline' }}>Current Information Required</span>
        . YOU MUST PROVIDE CURRENT, COMPLETE, AND ACCURATE INFORMATION FOR YOUR BILLING ACCOUNT. YOU MUST PROMPTLY UPDATE ALL INFORMATION TO KEEP YOUR BILLING ACCOUNT CURRENT, COMPLETE, AND ACCURATE (SUCH AS A CHANGE IN BILLING ADDRESS, CREDIT CARD NUMBER, OR CREDIT CARD EXPIRATION DATE), AND YOU MUST PROMPTLY NOTIFY US OR OUR PAYMENT PROCESSOR IF YOUR PAYMENT METHOD IS CANCELED (E.G., FOR LOSS OR THEFT) OR IF YOU BECOME AWARE OF A POTENTIAL BREACH OF SECURITY, SUCH AS THE UNAUTHORIZED DISCLOSURE OR USE OF YOUR USER NAME OR PASSWORD. CHANGES TO SUCH INFORMATION CAN BE MADE AT ACCOUNT SETTINGS. IF YOU FAIL TO PROVIDE ANY OF THE FOREGOING INFORMATION, YOU AGREE THAT WE MAY CONTINUE CHARGING YOU FOR ANY USE OF THE SERVICES UNDER YOUR BILLING ACCOUNT UNLESS YOU HAVE TERMINATED THE SERVICES AS SET FORTH ABOVE.
      </p>
      <p>
        <span style={{ textDecoration: 'underline' }}>Change in Amount Authorized</span>
        . If the amount to be charged to your Billing Account varies from the amount you preauthorized (other than due to the imposition or change in the amount of state sales taxes), you have the right to receive, and we shall provide, notice of the amount to be charged and the date of the charge before the scheduled date of the transaction. Any agreement you have with your payment provider will govern your use of your Payment Method. You agree that we may accumulate charges incurred and submit them as one or more aggregate charges during or at the end of each billing cycle.
      </p>
      <p>
        <span style={{ textDecoration: 'underline' }}>Auto-Renewal for the Services</span>
        . Unless you opt out of auto-renewal, which can be done through your account settings, any Services you have signed up for will be automatically extended for successive renewal periods of the same duration as the subscription term originally selected, at the then-current non-promotional rate. To change or resign your Services at any time, go to account settings. If you terminate the Services, you may use your subscription until the end of your then-current term, and your subscription will not be renewed after your then-current term expires. However, you will not be eligible for a prorated refund of any portion of the subscription fee paid for the then-current subscription period. IF YOU DO NOT WANT TO CONTINUE TO BE CHARGED ON A RECURRING MONTHLY BASIS, YOU MUST CANCEL THE SERVICES THROUGH YOUR ACCOUNT SETTINGS OR TERMINATE YOUR BLOCKSPACES ACCOUNT BEFORE THE END OF THE RECURRING TERM. THE SERVICES CANNOT BE TERMINATED BEFORE THE END OF THE PERIOD FOR WHICH YOU HAVE ALREADY PAID, AND EXCEPT AS EXPRESSLY PROVIDED IN THESE TERMS, BLOCKSPACES WILL NOT REFUND ANY FEES THAT YOU HAVE ALREADY PAID.
      </p>
      <p>
        <span style={{ textDecoration: 'underline' }}>Reaffirmation of Authorization</span>
        . Your non-termination or continued use of the Services reaffirms that we are authorized to charge your Payment Method for the Services. We may submit those charges for payment, and you will be responsible for such charges. This does not waive our right to seek payment directly from you. Your charges may be payable in advance, in arrears, per usage, or as otherwise described when you initially selected to use the Services.
      </p>
      <h5><em>Term &amp; Termination</em></h5>
      <p>The term of this Agreement will begin on the date you first submit a ticket for the Services. You are free to terminate at any time by contacting us at <a href="mailto:contact@blockspaces.com">contact@blockspaces.com</a>. Please refer to our Privacy Policy <a href="https://www.blockspaces.com/legal/privacy-policy" target={"_blank"}>https://www.blockspaces.com/legal/privacy-policy</a>, as well as the licenses above, to understand how we treat information you provide to us after you have stopped using the Services.</p>
      <p>BlockSpaces is also free to terminate (or suspend access to) your use of the Services or your account for any reason in our discretion, including your breach of these Terms. BlockSpaces has the sole right to decide whether you are in violation of any of the restrictions set forth in these Terms.</p>
      <p>Account termination may result in destruction of any Content associated with your account, so keep that in mind before you decide to terminate your account.</p>
      <p>If you have deleted your account by mistake, contact us immediately at <a href="mailto:contact@blockspaces.com">contact@blockspaces.com</a> – we will try to help, but unfortunately, we can’t promise that we can recover or restore anything.</p>
      <p>Provisions that, by their nature, should survive termination of these Terms shall survive termination. By way of example, all of the following will survive termination: any obligation you have to pay us or indemnify us, any limitations on our liability, any terms regarding ownership or intellectual property rights, and terms regarding disputes between us, including without limitation the arbitration agreement.</p>
      <h5><em>Change of Terms and Conditions</em></h5>
      <p>We are constantly trying to improve our Services, so these Terms may need to change along with our Services. We reserve the right to change the Terms at any time, but if we do, we will place a notice on our site located at <a href="https://www.blockspaces.com" target={"_blank"}>https://www.blockspaces.com</a>, send you an email, and/or notify you by some other means.</p>
      <p>If you disagree with the new Terms, you are free to reject them; unfortunately, that means you will no longer be able to use the Services. If you use the Services in any way after a change to the Terms is effective, that means you agree to all of the changes.</p>
      <p>Except for changes by us as described here, no other amendment or modification of these Terms will be effective unless in writing and signed by both you and us.</p>
      <h5><em>Privacy Policy</em></h5>
      <p>BlockSpaces takes the privacy of its users very seriously, and protecting your privacy is a key feature of our Services. For the current BlockSpaces’ Privacy Policy, please check out <a href="https://www.blockspaces.com/legal/privacy-policy" target={"_blank"}>https://www.blockspaces.com/legal/privacy-policy</a>.</p>
      <h5><em>Warranty Disclaimer</em></h5>
      <p>Neither BlockSpaces nor its licensors, suppliers, partners, parent, subsidiaries or affiliated entities, and each of their respective officers, directors, members, employees, consultants, contract employees, representatives and agents, and each of their respective successors and assigns (BlockSpaces and all such parties together, the “BlockSpaces Parties”) makes any representations or warranties concerning the Services, including without limitation any Content contained in or accessed through the Services, and the BlockSpaces Parties will not be responsible or liable for the accuracy, copyright compliance, legality, or decency of material contained in or accessed through the Services or any claims, actions, suits procedures, costs, expenses, damages or liabilities arising out of or in any way related to your participation in or use of the Services. The BlockSpaces Parties make no representations or warranties regarding suggestions or recommendations of services or products offered or purchased through or in connection with the Services, including any Network services. THE SERVICES AND CONTENT ARE PROVIDED BY BLOCKSPACES ON AN “AS-IS” BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING, WITHOUT LIMITATION, IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, OR THAT USE OF THE SERVICES WILL BE UNINTERRUPTED OR ERROR-FREE. BLOCKSPACES MAKES NO REPRESENTATIONS OR WARRANTIES WITH REGARD TO CHAIN HALTS, THE NUMBER OF RELAYS, CRITICAL BUGS OR ERRORS IN THE PROTOCOL, OR THE STAKING REWARDS THAT MAY BE GENERATED OR RECEIVED BY YOU IN CONNECTION WITH THE SERVICES. FURTHERMORE, BLOCKSPACES HAS NO OBLIGATION TO PROVIDE ANY FUTURE RELEASES OR UPGRADES, FEATURES, ENHANCEMENTS, OR FUNCTIONS. SOME STATES DO NOT ALLOW LIMITATIONS ON HOW LONG AN IMPLIED WARRANTY LASTS, SO THE ABOVE LIMITATIONS MAY NOT APPLY TO YOU.</p>
      <h5><em>Limitation of Liability</em></h5>
      <p>TO THE FULLEST EXTENT ALLOWED BY APPLICABLE LAW, UNDER NO CIRCUMSTANCES AND UNDER NO LEGAL THEORY (INCLUDING, WITHOUT LIMITATION, TORT, CONTRACT, STRICT LIABILITY, OR OTHERWISE) SHALL ANY OF THE BLOCKSPACES PARTIES BE LIABLE TO YOU OR TO ANY OTHER PERSON FOR (A) ANY INDIRECT, SPECIAL, INCIDENTAL, PUNITIVE OR CONSEQUENTIAL DAMAGES OF ANY KIND, INCLUDING DAMAGES FOR LOST PROFITS, BUSINESS INTERRUPTION, LOSS OF DATA, LOSS OF GOODWILL, WORK STOPPAGE, ACCURACY OF RESULTS, OR COMPUTER FAILURE OR MALFUNCTION, (B) ANY SUBSTITUTE GOODS, SERVICES OR TECHNOLOGY, (C) ANY AMOUNT, IN THE AGGREGATE, IN EXCESS OF THE GREATER OF (I) ONE-HUNDRED ($100) DOLLARS OR (II) THE AMOUNTS PAID AND/OR PAYABLE BY YOU TO BLOCKSPACES IN CONNECTION WITH THE SERVICES IN THE TWELVE (12) MONTH PERIOD PRECEDING THIS APPLICABLE CLAIM OR (D) ANY FORCE MAJEURE EVENT OR OTHER MATTER BEYOND OUR CONTROL. SPECIFICALLY, BLOCKSPACES SHALL NOT, UNDER ANY CIRCUMSTANCES, BE LIABLE FOR ANY LOSSES ARISING FROM OR AS A RESULT OF (I) SLASHING PENALTIES; (II) THE RULES AND OPERATIONS OF A BLOCKCHAIN PROTOCOL OR ANY CHANGES THERETO; OR (III) NETWORK DOWNTIME, STALLS, OVERLOAD, OR SIMILAR NETWORK EVENT WHICH MAY IMPACT AVAILABILITY OF THE SERVICES. SOME STATES DO NOT ALLOW THE EXCLUSION OR LIMITATION OF INCIDENTAL OR CONSEQUENTIAL, OR CERTAIN OTHER DAMAGES, SO THE ABOVE LIMITATION AND EXCLUSIONS MAY NOT APPLY TO YOU.</p>
      <h5><em>Indemnity</em></h5>
      <p>To the fullest extent allowed by applicable law, You agree to indemnify and hold the BlockSpaces Parties (for purposes of this section, collectively, the “Indemnitee”) harmless from and against any and all claims, liabilities, damages (actual and consequential), losses and expenses (including attorneys’ fees) arising from or in any way related to any claims relating to (a) your use of the Services (including any actions taken by a third party using your account), and (b) your violation of this Agreement. In the event of such a claim, suit, or action (“Claim”), we will attempt to provide notice of the Claim to the contact information we have for your account (provided that failure to deliver such notice shall not eliminate or reduce your indemnification obligations hereunder). To the extent that the Indemnitee is or may be made a witness or otherwise asked or required to participate in any proceeding in which such Indemnitee is not a party, or receives a subpoena in any proceeding to which Indemnitee is not a party, Indemnitee shall be advanced all reasonable expenses and indemnified against all expenses actually and reasonably incurred by Indemnitee or on Indemnitee’s behalf in connection therewith, including attorneys’ fees.</p>
      <h5><em>Assignment</em></h5>
      <p>You may not assign, delegate or transfer these Terms or your rights or obligations hereunder, or your Services account, in any way (by operation of law or otherwise) without BlockSpaces' prior written consent. We may transfer, assign, or delegate these Terms and our rights and obligations without consent.</p>
      <h5><em>Choice of Law</em></h5>
      <p>These Terms are governed by and will be construed under the Federal Arbitration Act, applicable federal law, and the laws of the State of Florida, without regard to the conflicts of laws provisions thereof.</p>
      <h5><em>Arbitration Agreement and Class Action Waiver</em></h5>
      <p>PLEASE READ THE FOLLOWING ARBITRATION AGREEMENT CAREFULLY BECAUSE IT REQUIRES YOU TO ARBITRATE CERTAIN DISPUTES AND CLAIMS WITH BLOCKSPACES AND LIMITS THE MANNER IN WHICH YOU CAN SEEK RELIEF FROM BLOCKSPACES.</p>
      <p>Both you and BlockSpaces acknowledge and agree that for the purposes of any dispute arising out of or relating to the subject matter of these Terms, BlockSpaces' officers, directors, employees and independent contractors (“Personnel”) are third-party beneficiaries of these Terms, and that upon your acceptance of these Terms, Personnel will have the right (and will be deemed to have accepted the right) to enforce these Terms against you as the third-party beneficiary hereof.</p>
      <p><i>(a) Arbitration Rules; Applicability of Arbitration Agreement</i>. The parties shall use their best efforts to settle any dispute, claim, question, or disagreement arising out of or relating to the subject matter of these Terms directly through good-faith negotiations, which shall be a precondition to either party initiating arbitration. If such negotiations do not resolve the dispute, it shall be finally settled by binding arbitration in Hillsborough County, Florida. The arbitration will proceed in the English language, in accordance with the JAMS Streamlined Arbitration Rules and Procedures (the “Rules”), then in effect, by one commercial arbitrator with substantial experience in resolving intellectual property and commercial contract disputes. The arbitrator shall be selected from the appropriate list of JAMS arbitrators in accordance with such Rules. Judgment upon the award rendered by such arbitrator may be entered in any court of competent jurisdiction.</p>
      <p><i>(b) Costs of Arbitration</i>. The Rules will govern the payment of all arbitration fees.</p>
      <p><i>(c) Small Claims Court; Infringement</i>. Either you or BlockSpaces may assert claims, if they qualify, in small claims court in Hillsborough County, Florida. Furthermore, notwithstanding the foregoing obligation to arbitrate disputes, each party shall have the right to pursue injunctive or other equitable relief at any time from any court of competent jurisdiction to prevent the actual or threatened infringement, misappropriation, or violation of a party's copyrights, trademarks, trade secrets, patents or other intellectual property rights.</p>
      <p><i>(d) Waiver of Jury Trial</i>. YOU AND BLOCKSPACES WAIVE ANY CONSTITUTIONAL AND STATUTORY RIGHTS TO GO TO COURT AND HAVE A TRIAL IN FRONT OF A JUDGE OR JURY. You and BlockSpaces are instead choosing to have claims and disputes resolved by arbitration. Arbitration procedures are typically more limited, more efficient, and less costly than rules applicable in court and are subject to very limited review by a court. In any litigation between you and BlockSpaces over whether to vacate or enforce an arbitration award, YOU AND BLOCKSPACES WAIVE ALL RIGHTS TO A JURY TRIAL AND ELECT INSTEAD TO HAVE THE DISPUTE BE RESOLVED BY A JUDGE.</p>
      <p><i>(e) Waiver of Class or Consolidated Actions</i>. ALL CLAIMS AND DISPUTES WITHIN THE SCOPE OF THIS ARBITRATION AGREEMENT MUST BE ARBITRATED OR LITIGATED ON AN INDIVIDUAL BASIS AND NOT ON A CLASS BASIS. CLAIMS OF MORE THAN ONE CUSTOMER OR USER CANNOT BE ARBITRATED OR LITIGATED JOINTLY OR CONSOLIDATED WITH THOSE OF ANY OTHER CUSTOMER OR USER. If, however, this waiver of class or consolidated actions is deemed invalid or unenforceable, neither you nor BlockSpaces is entitled to arbitration; instead, all claims and disputes will be resolved in a court as outlined in (g) below.</p>
      <p><i>(f)Exclusive Venue</i>. If any of the foregoing arbitration agreement provisions are held to be invalid or unenforceable or you or BlockSpaces must otherwise litigate any dispute arising out of or relating to the subject matter of these Terms in court, then the foregoing arbitration agreement will not apply to either party, and both you and BlockSpaces agree that any judicial proceeding (other than small claims actions) will be brought in the state or federal courts located in, respectively, Hillsborough County, Florida, or the federal district in which that county falls.</p>
      <p><i>(g) Severability</i>. If the prohibition against class actions and other claims brought on behalf of third parties contained above is found to be unenforceable, then all of the preceding language in this Arbitration Agreement section will be null and void. This arbitration agreement will survive the termination of your relationship with BlockSpaces.</p>
      <h5><em>Force Majeure</em></h5>
      <p>BlockSpaces is excused from any delay or failure in performance of this Agreement to the extent such delay or failure is caused by or a result of wildfire, flood, explosion, war, embargo, governmental requirement, civil or military authority, Act of God, pandemics, epidemics, or government ordered quarantine, the governing rules of the Protocol, a change in Protocol, Network maintenance, Network downtime, stalls, overload or similar Network event which may impact availability of the Services, your acts and omissions, the acts or omissions of a hacker or other bad actor, or other events beyond the control of BlockSpaces (collectively, “Force Majeure Events”). Any such delay or failure will suspend BlockSpaces’ obligations to perform under the Agreement until the cause for the delay or failure is removed or rectified.</p>
      <h5><em>Miscellaneous</em></h5>
      <p>You will be responsible for paying, withholding, filing, and reporting all taxes, duties, and other governmental assessments associated with your activity in connection with the Services. BlockSpaces does not and will not provide any advice or guidance with respect to your tax obligations. We strongly encourage you to seek advice from a tax advisor regarding your staking activities under this Agreement. The failure of either you or us to exercise, in any way, any right herein shall not be deemed a waiver of any further rights hereunder. If any provision of these Terms is found to be unenforceable or invalid, that provision will be limited or eliminated, to the minimum extent necessary, so that these Terms shall otherwise remain in full force and effect and enforceable. You and BlockSpaces agree that these Terms are the complete and exclusive statement of the mutual understanding between you and BlockSpaces and that these Terms supersede and cancel all previous written and oral agreements, communications, and other understandings relating to the subject matter of these Terms. You hereby acknowledge and agree that you are not an employee, agent, partner, or joint venture of BlockSpaces, and you do not have any authority of any kind to bind BlockSpaces in any respect whatsoever.</p>
      <p>Except as expressly outlined in the sections above regarding the arbitration agreement, you and BlockSpaces agree there are no third-party beneficiaries intended under these Terms.</p>
    </>
  );
}