import * as React from "react";
import * as ReactDOM from "react-dom";

type PortalProps = {
  children: React.ReactElement;
  container?: HTMLElement | null;
  bubble?: boolean;
};

export const Portal: React.FC<React.PropsWithChildren<PortalProps>> = (props) => {
  const body = globalThis?.document?.body;
  const { bubble = false, children, container = body } = props;
  const child = bubble ? children : React.cloneElement(React.Children.only(children), events);
  return container ? ReactDOM.createPortal(child, container) : null;
};

type ReactEvents = keyof Omit<React.DOMAttributes<any>, "children" | "dangerouslySetInnerHTML" | "onPointerEnterCapture" | "onPointerLeaveCapture">;

const stopPropagation = (event: any) => event.stopPropagation();
type Events<T extends ReactEvents> = { [K in T]: typeof stopPropagation };


const events: Events<ReactEvents> = {
  onCopy: stopPropagation,
  onCopyCapture: stopPropagation,
  onCut: stopPropagation,
  onCutCapture: stopPropagation,
  onPaste: stopPropagation,
  onPasteCapture: stopPropagation,
  onCompositionEnd: stopPropagation,
  onCompositionEndCapture: stopPropagation,
  onCompositionStart: stopPropagation,
  onCompositionStartCapture: stopPropagation,
  onCompositionUpdate: stopPropagation,
  onCompositionUpdateCapture: stopPropagation,
  onFocus: stopPropagation,
  onFocusCapture: stopPropagation,
  onBlur: stopPropagation,
  onBlurCapture: stopPropagation,
  onChange: stopPropagation,
  onChangeCapture: stopPropagation,
  onBeforeInput: stopPropagation,
  onBeforeInputCapture: stopPropagation,
  onInput: stopPropagation,
  onInputCapture: stopPropagation,
  onReset: stopPropagation,
  onResetCapture: stopPropagation,
  onSubmit: stopPropagation,
  onSubmitCapture: stopPropagation,
  onInvalid: stopPropagation,
  onInvalidCapture: stopPropagation,
  onLoad: stopPropagation,
  onLoadCapture: stopPropagation,
  onError: stopPropagation,
  onErrorCapture: stopPropagation,
  onKeyDown: stopPropagation,
  onKeyDownCapture: stopPropagation,
  onKeyPress: stopPropagation,
  onKeyPressCapture: stopPropagation,
  onKeyUp: stopPropagation,
  onKeyUpCapture: stopPropagation,
  onAbort: stopPropagation,
  onAbortCapture: stopPropagation,
  onCanPlay: stopPropagation,
  onCanPlayCapture: stopPropagation,
  onCanPlayThrough: stopPropagation,
  onCanPlayThroughCapture: stopPropagation,
  onDurationChange: stopPropagation,
  onDurationChangeCapture: stopPropagation,
  onEmptied: stopPropagation,
  onEmptiedCapture: stopPropagation,
  onEncrypted: stopPropagation,
  onEncryptedCapture: stopPropagation,
  onEnded: stopPropagation,
  onEndedCapture: stopPropagation,
  onLoadedData: stopPropagation,
  onLoadedDataCapture: stopPropagation,
  onLoadedMetadata: stopPropagation,
  onLoadedMetadataCapture: stopPropagation,
  onLoadStart: stopPropagation,
  onLoadStartCapture: stopPropagation,
  onPause: stopPropagation,
  onPauseCapture: stopPropagation,
  onPlay: stopPropagation,
  onPlayCapture: stopPropagation,
  onPlaying: stopPropagation,
  onPlayingCapture: stopPropagation,
  onProgress: stopPropagation,
  onProgressCapture: stopPropagation,
  onRateChange: stopPropagation,
  onRateChangeCapture: stopPropagation,
  onSeeked: stopPropagation,
  onSeekedCapture: stopPropagation,
  onSeeking: stopPropagation,
  onSeekingCapture: stopPropagation,
  onStalled: stopPropagation,
  onStalledCapture: stopPropagation,
  onSuspend: stopPropagation,
  onSuspendCapture: stopPropagation,
  onTimeUpdate: stopPropagation,
  onTimeUpdateCapture: stopPropagation,
  onVolumeChange: stopPropagation,
  onVolumeChangeCapture: stopPropagation,
  onWaiting: stopPropagation,
  onWaitingCapture: stopPropagation,
  onAuxClick: stopPropagation,
  onAuxClickCapture: stopPropagation,
  onClick: stopPropagation,
  onClickCapture: stopPropagation,
  onContextMenu: stopPropagation,
  onContextMenuCapture: stopPropagation,
  onDoubleClick: stopPropagation,
  onDoubleClickCapture: stopPropagation,
  onDrag: stopPropagation,
  onDragCapture: stopPropagation,
  onDragEnd: stopPropagation,
  onDragEndCapture: stopPropagation,
  onDragEnter: stopPropagation,
  onDragEnterCapture: stopPropagation,
  onDragExit: stopPropagation,
  onDragExitCapture: stopPropagation,
  onDragLeave: stopPropagation,
  onDragLeaveCapture: stopPropagation,
  onDragOver: stopPropagation,
  onDragOverCapture: stopPropagation,
  onDragStart: stopPropagation,
  onDragStartCapture: stopPropagation,
  onDrop: stopPropagation,
  onDropCapture: stopPropagation,
  onMouseDown: stopPropagation,
  onMouseDownCapture: stopPropagation,
  onMouseEnter: stopPropagation,
  onMouseLeave: stopPropagation,
  onMouseMove: stopPropagation,
  onMouseMoveCapture: stopPropagation,
  onMouseOut: stopPropagation,
  onMouseOutCapture: stopPropagation,
  onMouseOver: stopPropagation,
  onMouseOverCapture: stopPropagation,
  onMouseUp: stopPropagation,
  onMouseUpCapture: stopPropagation,
  onSelect: stopPropagation,
  onSelectCapture: stopPropagation,
  onTouchCancel: stopPropagation,
  onTouchCancelCapture: stopPropagation,
  onTouchEnd: stopPropagation,
  onTouchEndCapture: stopPropagation,
  onTouchMove: stopPropagation,
  onTouchMoveCapture: stopPropagation,
  onTouchStart: stopPropagation,
  onTouchStartCapture: stopPropagation,
  onPointerDown: stopPropagation,
  onPointerDownCapture: stopPropagation,
  onPointerMove: stopPropagation,
  onPointerMoveCapture: stopPropagation,
  onPointerUp: stopPropagation,
  onPointerUpCapture: stopPropagation,
  onPointerCancel: stopPropagation,
  onPointerCancelCapture: stopPropagation,
  onPointerEnter: stopPropagation,
  onPointerLeave: stopPropagation,
  onPointerOver: stopPropagation,
  onPointerOverCapture: stopPropagation,
  onPointerOut: stopPropagation,
  onPointerOutCapture: stopPropagation,
  onGotPointerCapture: stopPropagation,
  onGotPointerCaptureCapture: stopPropagation,
  onLostPointerCapture: stopPropagation,
  onLostPointerCaptureCapture: stopPropagation,
  onScroll: stopPropagation,
  onScrollCapture: stopPropagation,
  onWheel: stopPropagation,
  onWheelCapture: stopPropagation,
  onAnimationStart: stopPropagation,
  onAnimationStartCapture: stopPropagation,
  onAnimationEnd: stopPropagation,
  onAnimationEndCapture: stopPropagation,
  onAnimationIteration: stopPropagation,
  onAnimationIterationCapture: stopPropagation,
  onTransitionEnd: stopPropagation,
  onTransitionEndCapture: stopPropagation,
  onResize: stopPropagation,
  onResizeCapture: stopPropagation
};
